version: '2.1'

services:
    rt1:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        command: ["tcpdump", "-nSt", "icmp"]
        networks:
            - tnet2
    rt2:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        depends_on:
            - rt1
        command: ["ping", "-s", "4000", "rt1"]
        networks:
            - tnet2
    rt3:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        depends_on:
            - rt1
        command: ["ping", "rt1"]
        sysctls:
            - net.ipv4.icmp_echo_ignore_all=1
        networks:
            - tnet2
    rt4:
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        depends_on:
            - rt3
        command: ["ping", "-c", "1", "rt3"]
        networks:
            - tnet2
    tn1:
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        command: "bash -c 'echo \"- interfetele de retea:\" && ip addr && echo \"- gateway:\" && ip route show'"
        networks:
           - tnet1

networks:
    tnet2:
        ipam:
            driver: default
            config:
                - subnet: 1.2.3.5/16 
                  gateway: 1.2.3.4
    tnet1:
        ipam:
            driver: default
            config:
                - subnet: 15.08.96.10/16
                  gateway: 15.08.15.1
